@startuml Use Case Template
!include_once ../style.iuml
' other includes, e.g., !include_once users.iuml

(My Use Case) as UC1
actor :My Actor: as A
A -- UC1
@enduml

# Name

My Use Case

# Participating Actors

- My Actor
- My Other Actor

# Preconditions

> Optional

- A
- B
- C

# Flow of Events

1. A
2. B
3. C

# Alternative Flow of Events

> Optional

1a. U
2a. V
3a. W

# Postconditions

> Optional

- D
- E
- F

# Quality Requirements

> Optional

- 1
- 2
- 3