@startuml CreateSession
actor :Admin:

rectangle "Sessions" {
  (Assign Session) as Assign
}
Admin -- Assign
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated
- Session exists

# Flow of Events

1. Admin clicks edit on existing session
2. admin assigns mentor to session
3. mentor is notified of the change

# Quality Requirements

- Should notify the mentor when they get assigned to a session
