@startuml CreateSession
actor :Admin:

rectangle "Sessions" {
  (Assign Session) as Assign
}
Admin -- Assign
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin clicks edit on an "Assign Session" button
2. The Admin selects a Mentor to assign
3. The Admin clicks a "Save" button
4. The Mentor is notified of the assignment