@startuml Close Occurence
rectangle "Occurrences"{
(Close Occurrence)
(Review Occurrence)
}
actor :Admin:
Admin -- (Close Occurrence)
(Close Occurrence) .> (Review Occurrence): <<extend>>

@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated
- This use case **extends** ReviewOccurrence, and is initiated when the Admin clicks a "Close" button in the menu of an Occurrence

# Flow of Events

2. The system notifies the Mentor the Occurrence is associated with that the Occurrence was closed
1. The system displays a confirmation message