@startuml Close Occurence
rectangle "Occurrences"{
(Close Occurrence)
(Review Occurrence)
}
actor :Admin:
Admin -- (Close Occurrence)
(Close Occurrence) .> (Review Occurrence): <<extend>>

@enduml

# Participating Actors

- Admin

# Preconditions

- Admin Loged in
- Has Occurrence included

# Flow of Events

1. Admin clicks on Close Occurrence
    2. System sets Occurence to closed

# Alternative Flow of Events


# Postconditions
Admin loged in
Occurrence is Closed

# Quality Requirements

User interface is clean.