@startuml Configure Action Types
package "Penalty Score Management"{
(Configure Action Types)
}
actor :Admin:
Admin -up- (Configure Action Types)
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin clicks a "Configure Action Types" button
2. The system displays an edit list of Actions
3. The Admin edits the Actions
4. The Admin clicks a "Save" button
5. The system displays a confirmation message

# Alternative Flow of Events

4a. The Admin clicks a "Cancel" button
5a. The system prompts the Admin if they are sure they want to discard the Actions
6a. The Admin clicks a "Yes" button
7a. The system discards the changes and displays a confirmation message
6b. The Admin clicks a "No" button
7b. The system returns the Admin to the list

@startuml Configure Action Types Object Model
class ConfigureActionTypes <<control>> {}
class ActionTypeList <<entity>> {}
ConfigureActionTypes --> ActionTypeList
class ActionType <<entity>> {
  + name: String
}
ActionTypeList "1" o-- "*" ActionType
Action --> "+ type" ActionType
@enduml