@startuml Configure Notification Preferences
actor :Mentor:
rectangle "Notifications" {
  (Configure Notification Preferences) as notifPref
}
Mentor -- notifPref
@enduml

# Participating Actors

- Mentor

# Preconditions

- The Mentor is authenticated

# Flow of Events

1. Mentor selects the notifcations they want to receive/send
2. Mentor clicks a "Save" button
3. System saves the notification preferences
