@startuml My Use Case
actor :Admin:
rectangle "Occurrences" {
  (Configure Default Actions\nfor Occurrences) as ConfDefActOcc
}
Admin -- ConfDefActOcc
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin clicks a "Configure Default Actions" button
2. The system displays a list of Occurrence Types and dropdowns to select Actions
3. The Admin edits the drop downs
4. The Admin clicks a "Save" button
5. The system displays a confirmation message

# Alternative Flow of Events

4a. The Admin clicks a "Cancel" button
5a. The system prompts the Admin if they are sure they want to discard the changes
6a. The Admin clicks a "Yes" button
7a. The system discards the changes and displays a confirmation message
6b. The Admin clicks a "No" button
7b. The system returns the Admin to the list