@startuml Configure Notification Preferences
actor :Mentor:
package "Notifications" {
  (Configure Notification Preferences) as notifPref
}
Mentor -right- notifPref
@enduml

# Participating Actors

- Mentor

# Preconditions

- The Mentor is authenticated

# Flow of Events

1. The Mentor selects the Notifications they want to receive
2. The Mentor clicks a "Save" button
3. The system saves the notification preferences
