@startuml Configure Action Types
rectangle "Penalty Score Management"{
(Configure Action Types)
}
actor :Admin:
Admin -- (Configure Action Types)
@enduml

# Participating Actors

- Admin

# Preconditions
- The Admin is authenticated

# Flow of Events

1. Admin Presses Configure Action Types
    2.System displyes presently avalable Actions 
    3.System diplays add Action type
4. Admin Presses Configure action on a action
    5. Sytem Displys curent options in editalbe fields
6.Admin edits action and saves, system saves changes

# Alternative Flow of Events

4a. Admin Presses Add action type
    5a. Sytem Displys curent options in editalbe fields
6a. Admin creates action and saves, system saves changes

# Postconditions

-Admin Loged in