@startuml Configure Tardiness Intervals
actor :Admin:
package "Penalty Score Management" {
  (Configure Tardiness Intervals) as ConfTardInt
}
Admin -up- ConfTardInt
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin clicks a "Edit Tardiness Intervals" button
2. The system displays a editable list of of Tardiness Intervals and their Point values
3. The Admin edits the Tardiness Intervals
4. The Admin clicks a "Save" button
5. The system displays a confirmation message

# Alternative Flow of Events

5a. If any of the intervals overlap or are not in increasing order, then the system displays an error message and returns the Admin to the list

# Quality Requirements

- The intervals should be displayed in minutes
- Other than the first interval, the start time of each interval should be fixed as the end time of the previous interval

@startuml Configure Tardiness Intervals Object Model
class ConfigureTardinessIntervals <<control>> {}
class TardinessIntervalList <<boundary>> {}
ConfigureTardinessIntervals --> TardinessIntervalList
class TardinessInterval <<entity>> {
  + minutes: Integer
  + points: Integer
}
TardinessIntervalList "1" o-- "*" TardinessInterval
@enduml