@startuml CreateSession
actor :Mentor:
actor :Admin:

package "Sessions" {
  (Create Session) as create
}
Admin - create
Mentor -- create
@enduml

# Participating Actors

- Admin
- Mentor

# Preconditions

- The Admin is authenticated
- The Mentor is authenticated

# Flow of Events

1. The Mentor requests to create a session
2. The Admin receives the request
3. The Admin approves the request
4. The system notifies the Mentor of the approval

# Alternative Flow of Events

3a. The Admin rejects the request
4a. The system notifies the Mentor of the rejection

# Quality Requirements

- Button should be on the main page where all sessions are shown pending sessions should be displayed separately and if the user is an admin approve/denial should be next to it

@startuml Create Session Object Model
class CreateSession <<control>>
class CreateSessionForm <<boundary>>
class Mentor <<entity>> {}
class Session <<entity>> {
  + startTime: DateTimeOffset
}
CreateSession --> "+ form" CreateSessionForm
CreateSession --> Session
Session --> "+ mentor" Mentor
@enduml