@startuml Edit Profile
actor :Mentor:
rectangle "Mentor Profiles" {
  (Edit Profile) as Edit
}
Mentor -- Edit
@enduml

# Participating Actors

- Mentor

# Preconditions

- The Mentor is authenticated

# Flow of Events

1. The Mentor clicks an "Edit" button on their profile
2. The Mentor edits their personal information
3. The Mentor clicks a "Save" button
4. The system displays a confirmation message
