@startuml Edit Occurence
rectangle "Occurrences"{
(Edit Occurrence)
(Review Occurrence)
}
actor :Admin:
Admin -- (Edit Occurrence)
(Edit Occurrence) .> (Review Occurrence) : <<extend>>
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated
- This use case **extends** ReviewOccurrence, and is initiated when the Admin clicks an "Edit" button in the menu of an Occurrence

# Flow of Events

1. The system displays a form for editing the Occurrence Type, Point value, and Action.
2. The Admin makes changes to the Type, Point, or Action values
3. The Admin clicks a "Save" button
4. The system displays a confirmation message
5. The Admin is returned to the menu for the Occurrence that was edited

# Alternative Flow of Events

4a. Admin Clicks a "Cancel" button
    5a. The system promts the Admin to confirm discarding the changes
6a. The Admin clicks a "Yes" button
    7a. The system returns the Admin to the Occurrence menu
6b. The Admin clicks a "No" button 
    7a. the system returns the Admin to the form

# Postconditions

-Admin Loged in