@startuml Log Out
actor :User: <<abstract>>
package "Authentication" {
  (Log Out) as LogOut
}
User -up- LogOut
@enduml

# Participating Actors

- User

# Preconditions

- The User is authenticated

# Flow of Events

1. The User clicks a "Log out" button
2. The User confirms the log out action
3. The system displays a confirmation message


@startuml Log Out Object Model
class LogOut {}
class LogOutButton <<boundary>> {}
LogOut --> LogOutButton 
@enduml