@startuml MarkMentorAbsent
actor :Absence Timer: as AbsenceTimer
rectangle "Sessions" {
  (Mark Mentor as Absent) as MarkAbsent
}
rectangle "Occurrences" {
  (Report Occurrence) as Report
}
AbsenceTimer -- MarkAbsent
MarkAbsent ..> Report : <<include>>
@enduml

# Participating Actors

- Absence Timer

# Preconditions

- Mentor has Not Started Session
- Current Time greater than MaxTardinessInterval

# Flow of Events
1. Include ReportOccurence
2. System reports that the mentor is absent
