@startuml Mark Mentor as Tardy
actor :Mentor:
rectangle "Sessions" {
  (Start Session) as Start
  (Mark Mentor as Tardy) as Tardy
}
rectangle "Occurrences" {
  (Report Occurrence) as Report
}
Tardy .> Start : <<extend>>
Tardy ..> Report : <<include>>

@enduml

# Preconditions

- Session started when current time > TardinessInterval

# Flow of Events
1. Include ReportOccurence
2. System reports that the mentor was tardy
