@startuml Mark Mentor as Absent
actor :Absence Timer: as AbsenceTimer
rectangle "Sessions" {
  (Mark Mentor as Absent) as MarkAbsent
}
rectangle "Occurrences" {
  (Report Occurrence) as Report
}
AbsenceTimer -- MarkAbsent
MarkAbsent ..> Report : <<include>>
@enduml

# Participating Actors

- Absence Timer

# Preconditions

- The Mentor has Not Started Session
- The interval between the current time and the start time of the Session is greater than or equal to the maximum Tardiness Interval

# Flow of Events

1. **include** ReportOccurrence
