@startuml Mark Mentor as Tardy
package "Sessions" {
  (Start Session) as Start
  (Mark Mentor as Tardy) as Tardy
}
!include ReportOccurrence.iuml
Tardy .> Start : <<extend>>
Tardy ..> (Report Occurrence) : <<include>>

@enduml

# Preconditions

- This use case **extends** StartSession, and is initiated when the interval between the current time and the start time of the Session is greater than or equal to the minimum Tardiness Interval, but less than the maximum Tardiness Interval

# Flow of Events

1. **include** ReportOccurrence
