@startuml Mark Mentor as Absent
actor :Absence Timer: as AbsenceTimer
package "Sessions" {
  (Mark Mentor as Absent) as MarkAbsent
}
!include ReportOccurrence.iuml
AbsenceTimer -- MarkAbsent
MarkAbsent ..> (Report Occurrence) : <<include>>
@enduml

# Participating Actors

- Absence Timer

# Preconditions

- The Mentor has Not Started Session
- The interval between the current time and the start time of the Session is greater than or equal to the maximum Tardiness Interval

# Flow of Events

1. **include** ReportOccurrence

@startuml Mark Mentor as Absent Object Model
class MarkMentorAsAbsent <<control>> {}
MarkMentorAsAbsent --> Occurrence : Creates >
@enduml