@startuml Mentor Report Occurence
!include_once ../style.iuml
' other includes, e.g., !include_once users.iuml
(Mentor Report Occurence) as Mro
actor :Mentor: as M
actor :system: <<pasive>> as S
actor :admin: <<pasive>> as A


M -- Mro
Mro -- S
Mro --"1" A
@enduml

# Participating Actors

- mentor
- admin

# Preconditions

> Optional

- Mentor Loged in
- mentor conected to sys
- C

# Flow of Events

1. Mentor presses Report Occurence
    2. Opens report occurence menu
        3. mentor chooses occurence type (drop down list with other as a text box)
        4. mentor types description in description text box
        5. mentor enters mentors subject with potental auto fill depending on mentors current subject
        6. mentor enters date of occurence in date time field
    7. mentor slects they want to submit not anonamosly
    8. mentor clicks submit occurence
        9. sys logs time of submition of occurence
        10. sys logs the mentor that submited
        11.sys logs all feilds in occurence menu to new occurence in occurence admin list


# Alternative Flow of Events

> Optional

    7a. mentor slects they want to submit ananamulsy
    8a. mentor clicks submit occurence
        9a. sys logs time of submition of occurence
        10a.sys logs all feilds in occurence menu to new occurence in occurence adminlist

# Postconditions

> Optional

- mentor loged in
- mentor conected to sys
- F

# Quality Requirements

> Optional

- User interface is clean looking
- User interface is eazy to understand
- 3