@startuml Query Occurrence
package "Occurrences"{
(Query Occurrence)
}
actor :Admin:
Admin -- (Query Occurrence)
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin opens the Admin Summary Screen
2. The system displays a list of Occurrences, with filters for Occurrence Type and Status
3. The Admin changes the filters
4. The system updates the list to reflect the new filters

@startuml Query Occurrence Object Model
class QueryOccurrence <<control>> {}

QueryOccurrence "1" o-- "*" Occurrence

@enduml

