@startuml QueryMentorProfiles
actor :Admin:
rectangle "Mentor Profiles" {
  (Query Mentor Profiles) as QueryProf
}
Admin -- QueryProf
@enduml

/'
# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. Admin Clicks show Mentors
2. List of all Mentors displayed to the admin


# Quality Requirements
Should quickly show all mentor profiles in a easy to read list with a drop down (think 3 dots next to name) menu to access what the admin is allowed to edit (override profile, summarize, etc)
