@startuml Report Occurrence
rectangle "Occurrences"{
(Report Occurrence)
}
actor :Mentor:
Mentor -- (Report Occurrence)
@enduml

# Participating Actors

- Mentor

# Preconditions

- The Mentor is authenticated

# Flow of Events

1. The Mentor clicks a "Report Occurrence" button
2. The system displays a form with the Occurrence Type, description, subject, date, and whether to submit the Occurrence anonymously
3. The Mentor fills out the fields
4. The Mentor clicks on a "Submit Button"
5. The system displays a confirmation message

# Alternative Flow of Events

4a. The Mentor clicks a "Cancel" button
5a. The system prompts the Mentor if they are sure they want to discard the Occurrence
6a. The Mentor clicks a "Yes" button
7a. The system discards the Occurrence and displays a confirmation message
6b. The Mentor clicks a "No" button
7b. The system returns the Mentor to the form