@startuml Request Special Profile Edit
actor :Mentor:
actor :Admin:
package "Mentor Profiles" {
  (Request Special Profile Edit) as req
  (Edit Profile) as Edit
  req .> Edit : <<extends>>
}
Mentor -- req
Admin -- req
@enduml

# Participating Actors

- Mentor
- Admin

# Preconditions

- The Mentor is authenticated
- The Admin is authenticated
- This use case **extends** EditProfile, and is initiated when the Mentor edits their preferred name or profile picture

# Flow of Events

1. The Admin is notified of the request
2. The Admin approves the request
3. The system notifies the Mentor of the approval

# Alternative Flow of Events

2a. The Admin rejects the request
3a. The system notifies the Mentor of the rejection
