@startuml Review Occurence
rectangle "Occurrences"{
(Review Occurence) as RevOcc
}
actor :Admin:
Admin -- RevOcc

@enduml

# Participating Actors

- Admin
- sys

# Preconditions

- admin Loged in

# Flow of Events

1. Admin clicks on review Occurence
    2. System displyes all information of the occurence
    3. system displyes a notes page and buttons for action that the admin can take
4. Admin adds notes to Occurece
5. Admin exits the occurence review
6. system exits the occurence review and saves the notes and changes to occurence

# Alternative Flow of Events

5a. admin clicks close Occurence
6a. System sets the Occurence to Closed

# Postconditions
Admin loged in

# Quality Requirements

User interface is clean and dosent look like a windows prototype that is still there.