@startuml Review Occurrence
package "Occurrences"{
(Review Occurrence)
}
actor :Admin:
Admin -- (Review Occurrence)

@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin clicks on Occurrence in the Admin Summary Screen
2. The system displays a menu all information of the Occurrence
3. The system displays a form for taking notes on the Occurrence and buttons for the actions the Admin can do with the Occurrence (see CloseOccurrence and EditOccurrence)
4. The Admin add or edit the notes in the form
5. The Admin clicks a "Save" button
6. The system displays a confirmation message

@startuml Review Occurrence Object
class ReviewOccurrence <<control>>
class ReviewOccurrenceButton <<boundry>>
class ReviewOccurrenceForm <<boundry>> {
    + editOccurence()
    + CloseOccurence()
}
class Occurrence <<entity>> {
    +occurence: Occurence
}
ReviewOccurrence --> "+ button" ReviewOccurrenceButton
ReviewOccurrence --> "+ form" ReviewOccurrenceForm: reads >
ReviewOccurrence --> Occurrence
@enduml