@startuml Review Occurence
rectangle "Occurrences"{
(Review Occurrence)
}
actor :Admin:
Admin -- (Review Occurrence)

@enduml

# Participating Actors

- Admin

# Preconditions

- admin Loged in

# Flow of Events

1. Admin clicks on review Occurrence
    2. System displyes all information of the occurrence
    3. system displyes a notes page and buttons for action that the admin can take
4. Admin adds notes to Occurrece
5. Admin exits the occurrence review
6. system exits the occurrence review and saves the notes and changes to occurrence

# Alternative Flow of Events

5a. admin clicks close Occurrence
6a. System calls CloseOccurrence
7a. System exits the occurence review and saves the notes and changes to occurrence

# Postconditions
Admin loged in

# Quality Requirements

User interface is clean and dosent look like a windows prototype that is still there.