@startuml StartSession
actor :Mentor:
package "Sessions" {
  (Start Session) as Start
}
Mentor -- Start
@enduml


# Participating Actors

- Mentor

# Preconditions

- The Mentor is present
- The current time is less than the maximum Tardiness Interval

# Flow of Events

1. The Mentor clicks a "Start Session" button
2. The system displays a confirmation message

# Quality Requirements

- The system should display both when the Session needs to be started and when the Mentor is considered tardy/absent
