@startuml Summarize Mentor Activity
actor :Admin:
package "Mentor Profiles" {
  (Summarize Mentor Activity) as summarize
}
Admin -up- summarize
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin opens the Admin Summary Screen
2. The system displays a table of Mentor activities, including: profile changes (which they can approve/deny; see RequestSpecialProfileEdit), attendance points, behavior points, and total points.

@startuml Summarize Mentor Activity object
class SummariseMentorActivity <<control>>
class MentorActivityFome <<boundry>> {
  + Mentors: mentor[]
}
interface MentorActivity <<interface>> {
  + aproveDenyProfileChanges(aproval: Bolean)

}
SummariseMentorActivity
@enduml