@startuml Summarize Mentor Activity
actor :Admin:
package "Mentor Profiles" {
  (Summarize Mentor Activity) as summarize
}
Admin -up- summarize
@enduml

# Participating Actors

- Admin

# Preconditions

- The Admin is authenticated

# Flow of Events

1. The Admin opens the Admin Summary Screen
2. The system displays a table of Mentor activities, including: profile changes (which they can approve/deny; see RequestSpecialProfileEdit), attendance points, behavior points, and total points.

@startuml Summarize Mentor Activity object
class SummarizeMentorActivity <<control>> {}
class MentorSummaryTable <<boundary>> {}
SummarizeMentorActivity --> MentorSummaryTable
MentorSummaryTable "1" o-- "0..*" MentorSummary
class MentorSummary <<entity>> {
  + attendancePoints: Integer
  + behaviorPoints: Integer
  + totalPoints: Integer
  + mentor: Mentor
}
MentorSummary --> Mentor
MentorSummary "1" o-- "0..* + profileChanges" ProfileChangeRequest
@enduml