@startuml Tigers4Tigers Use Case Diagram
!include Authentication.iuml
!include MentorProfiles.iuml
!include Notifications.iuml
!include Occurrences.iuml
!include Sessions.iuml
!include PenaltyScoreManagement.iuml
note bottom of Mentor : Multiplicity belongs to\nassociation with Report\nOccurrence
@enduml