@startuml Occurrences
!include ../../style.iuml
left to right direction
!include ../ConfigureOccurrenceTypes.iuml
!include ../CloseOccurrence.iuml
!include ../ReviewOccurrence.iuml
!include ../ConfigureDefaultActionsForOccurrences.iuml
!include ../EditOccurrence.iuml
!include ../QueryOccurrence.iuml
!include ../ReportOccurrence.iuml
@enduml