@startuml Sessions
!include ../../style.iuml
left to right direction
!include ../StartSession.iuml
!include ../MarkMentorAsTardy.iuml
!include ../MarkMentorAsAbsent.iuml
!include ../AssignSession.iuml
!include ../CreateSession.iuml
@enduml